[theme]
# Primary accent color for interactive elements.
primaryColor = "#E694FF"

# Background color for the main content area.
backgroundColor = "transparent"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#9FB0BF"

# Color used for almost all text.
textColor = "#241341"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "monospace"
