[theme]
# Primary accent color for interactive elements.
primaryColor = "#999999"

# Background color for the main content area.
backgroundColor = "#EFF1E6"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#B6B7B2"

# Color used for almost all text.
textColor = "#241341"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"